import React, { forwardRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { LottoBall } from './LottoBall';
import ViewShot from 'react-native-view-shot';

interface ShareCardProps {
    numbers: number[];
    round: number;
    date: string;
}

export const ShareCard = forwardRef<ViewShot, ShareCardProps>(({ numbers, round, date }, ref) => {
    return (
        <ViewShot ref={ref} options={{ format: 'png', quality: 1 }}>
            <View className="bg-slate-900 p-8 w-[300px] items-center justify-center rounded-3xl border-4 border-slate-800">
                {/* Header */}
                <View className="items-center mb-6">
                    <View className="bg-indigo-500 px-3 py-1 rounded-full mb-3">
                        <Text className="text-white font-bold text-xs uppercase tracking-widest">Lucky Numbers</Text>
                    </View>
                    <Text className="text-white text-3xl font-black">{round}회차</Text>
                    <Text className="text-slate-400 text-xs font-medium mt-1">{date}</Text>
                </View>

                {/* Balls */}
                <View className="flex-row flex-wrap justify-center gap-2 mb-8">
                    {numbers.map((n) => (
                        <LottoBall key={n} number={n} size="md" />
                    ))}
                </View>

                {/* Footer */}
                <View className="items-center">
                    <Text className="text-slate-500 text-[10px] uppercase tracking-widest mb-1">Generated by</Text>
                    <Text className="text-white font-bold text-sm">Lotto 6/45 Pro</Text>
                </View>
            </View>
        </ViewShot>
    );
});
